# ==========================================
# CONFIGURACION GENERAL
# Formato: CONFIG, CLAVE, VALORES...
# ==========================================
CONFIG, LOG_FILE, ../../../logs/1.log
CONFIG, WHITELIST, 127.0.0.1, 192.168.1.0/24

# ==========================================
# REGLAS DEL MOTOR
# Formato: ID, ESTADO, UMBRAL, VENTANA_SEGUNDOS, SEVERIDAD, NOMBRE
# ==========================================
P001, ON, 5, 60, ALTA, Fuerza Bruta SSH
P002, ON, 20, 10, MEDIA, Escaneo de Puertos TCP
P003, OFF, 10, 120, ALTA, Fuerza Bruta Autenticacion Web